# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\NguyenCuong\DMT_Beats3_Scanner\GUI\Scanner_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 210)
        MainWindow.setMinimumSize(QtCore.QSize(350, 210))
        MainWindow.setMaximumSize(QtCore.QSize(350, 210))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(350, 210))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 251))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Wrapper = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.Wrapper.setStyleSheet("border: 1px solid #ccc;")
        self.Wrapper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Wrapper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Wrapper.setObjectName("Wrapper")
        self.Result_Label = QtWidgets.QLabel(self.Wrapper)
        self.Result_Label.setGeometry(QtCore.QRect(0, 25, 168, 184))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Result_Label.setFont(font)
        self.Result_Label.setStyleSheet("border: 1px solid #ccc; background-color: #fff;")
        self.Result_Label.setTextFormat(QtCore.Qt.AutoText)
        self.Result_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Result_Label.setObjectName("Result_Label")
        self.Result_Title = QtWidgets.QLabel(self.Wrapper)
        self.Result_Title.setGeometry(QtCore.QRect(0, 0, 168, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Result_Title.setFont(font)
        self.Result_Title.setStyleSheet("background-color: rgba(103, 155, 203, 246); color: #fff;")
        self.Result_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Result_Title.setObjectName("Result_Title")
        self.Camera_Title = QtWidgets.QLabel(self.Wrapper)
        self.Camera_Title.setGeometry(QtCore.QRect(168, 0, 182, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Camera_Title.setFont(font)
        self.Camera_Title.setStyleSheet("background-color: rgba(103, 155, 203, 246); color: #fff;")
        self.Camera_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Camera_Title.setObjectName("Camera_Title")
        self.Camera_Frame = QtWidgets.QLabel(self.Wrapper)
        self.Camera_Frame.setGeometry(QtCore.QRect(168, 24, 181, 186))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Camera_Frame.setFont(font)
        self.Camera_Frame.setStyleSheet("border: 1px solid #ccc; background-color: #fff;")
        self.Camera_Frame.setTextFormat(QtCore.Qt.AutoText)
        self.Camera_Frame.setAlignment(QtCore.Qt.AlignCenter)
        self.Camera_Frame.setObjectName("Camera_Frame")
        self.Update_Button = QtWidgets.QPushButton(self.Wrapper)
        self.Update_Button.setGeometry(QtCore.QRect(48, 184, 77, 23))
        self.Update_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Update_Button.setStyleSheet("background-color: #fff; border: 1px solid #ccc;")
        self.Update_Button.setObjectName("Update_Button")
        self.horizontalLayout.addWidget(self.Wrapper)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Result_Label.setText(_translate("MainWindow", "NONE"))
        self.Result_Title.setText(_translate("MainWindow", "RESULT"))
        self.Camera_Title.setText(_translate("MainWindow", "CAMERA"))
        self.Camera_Frame.setText(_translate("MainWindow", "CAMERA ERROR"))
        self.Update_Button.setText(_translate("MainWindow", "UPDATE"))
